---
name: CI

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        board:
          - esp32dev
        platform_override:
          - ""
          - "https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install jq
        run: sudo apt-get install -yq jq
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build examples
        run: PLATFORM_OVERRIDE=${{ matrix.platform_override }} ./build_examples.sh ${{ matrix.board }}
